### ISSUE TITLE
Status of this crate

### ISSUE THREAD

**Issue by dtolnay** [viperscape/iota#2]
@viperscape I noticed it has been 16 months since the most recent commit. Are you still planning on developing this crate? If not, I was hoping you might be willing to transfer the name so I could use it for [this little library](https://github.com/dtolnay/iota) which is based on [Go's iota feature](https://golang.org/ref/spec#Iota).

```
cargo owner --add dtolnay iota
```

**Comment by ferraracompany** [comment]
That's fine, if I continue this crate I'll rename it with subcrate names such as iota-udp, iota-handler; but that is looking unlikely.. just so many other projects ahead of this one. 
As an aside, it's common for crates that are parallel other languages to be post-fixed with '-rs', such as iota-rs. Just a thought! I'll try and get to this soon for you

**Comment by viperscape** [comment]
That's fine, if I continue this crate I'll rename it with subcrate names such as iota-udp, iota-handler; but that is looking unlikely.. just so many other projects ahead of this one.
As an aside, it's common for crates that are parallel other languages to be post-fixed with '-rs', such as iota-rs. Just a thought! I'll try and get to this soon for you

**Comment by dtolnay** [comment]
I appreciate it. This does look like a neat project so if you decide to continue it I would be happy to stick a link in my readme.

**Comment by viperscape** [comment]
I changed the ownership to add you, however after checking crates.io there is already a crate called iota-rs which looks like what you created: 
https://github.com/Popog/iota-rs
https://crates.io/search?q=iota

If you still want to convert this on crates.io that's fine, but it now seems redundant. Either way I think I will close this issue-- thanks for contributing to rust, it's a great language
